config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  resources :usuarios, only: [ :index, :new, :create ]
  resources :empresas, only: [ :index, :new, :create, :show ] do
    resources :vagas, only: [ :index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empresa.rb
class Empresa < ApplicationRecord
  has_many :vagas
  validates :nome, presence: true
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/models/vaga.rb
class Vaga < ApplicationRecord
  belongs_to :empresa
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController

  def index
    @empresas = Empresa.all
  end

  def show
    @empresa = Empresa.find(params[:id])
  end

  def new
    @empresa = Empresa.new
  end

  def create
    @empresa = Empresa.new(empresa_params)
    if @empresa.save
      redirect_to @empresa, notice: 'Empresa foi adicionada com sucesso.'
    else
      render :new
    end
  end

  private 

    def empresa_params
      params.require(:empresa).permit(:nome, :descricao)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  
  def index
    @usuarios = Usuario.all
  end

  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.new(usuario_params)
    if @usuario.save
      redirect_to @usuario, notice: 'Usuário criado com sucesso.'
    else
      render :new
    end
  end

  private 

  def usuario_params
    params.require(:usuario).permit(:nome, :email, :cargo)
  end

end

app/controllers/vagas_controller.rb
class VagasController < ApplicationController

  def index
    @vagas = Vaga.where(empresa_id: params[:empresa_id])
  end

  def show
    @vaga = Vaga.find(params[:id])
  end

  def new
    @vaga = Vaga.new
  end

  def create
    @vaga = Vaga.new(vaga_params)
    @vaga.empresa = Empresa.find(params[:id])

    if @vaga.save
      redirect_to vaga_path(@vaga), notice: "Vaga criada"
    else
      render :new
    end
  end

  def destroy
    @empresa = @vaga.empresa
    @vaga.destroy
    redirect_to @empresa
  end
  
  private 

    def vaga_params
      params.require(:vaga).permit(:nome, :skills)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/vagas_helper.rb
module VagasHelper
end

app/views/empresas/index.html.erb
<div class="container">
    <h3 class="titulo">Lista de Empresas</h3>
    <hr>
    <% @empresas.each do |empresa| %>
  <div class="card-product">
  <img src="https://image.flaticon.com/icons/png/512/43/43500.png" />
    <div class="card-product-infos">
      <div>
        <h2><%= empresa.nome %></h2>
        <p><%= empresa.descricao %></p>
      </div>
    </div>
      <%= link_to "Ver vagas", empresa_vagas_path(empresa), class: "btn btn-info" %>
  </div>
    <% end %>

</div>

app/views/empresas/new.html.erb
<h1>Formulário de Cadastro de Empresa</h1>

<%= simple_form_for @empresa do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <br>
  <br>
  <%= f.input :nome, :label => "Qual o nome da Empresa?" %>
  <br>
  <%= f.input :descricao, :label => "O que vocês fazem?" %>
  <br>
  <div class="btn-new">
  <%= f.button :submit, "Adicionar", class: "btn btn-outline-warning" %>
  </div>
      
<% end %>

app/views/empresas/show.html.erb
<div class="container">

  <h1><%= @empresa.nome %></h1>

  <h4>Descrição: <%= @empresa.descricao %></h4>

  <%= link_to "Vagas disponíveis", empresa_vagas_path(@empresa), class: "btn btn-info" %>
  <br>
  <%= link_to "Voltar", :back %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MATProvihack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-text">
    <h1>Step to tech</h1>
    <h2>Dê um pulo na sua carreira tech</h2>
    <%= link_to "Entrar", empresas_path, class: "btn btn-info" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-light navbar-light">
      <!-- Brand -->
      <%= link_to "Step to tech", root_path, class: "navbar-brand" %>

      <!-- Toggler/collapsibe Button -->
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#collapsibleNavbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar links -->
      <div class="collapse navbar-collapse justify-content-end cl-effect-14"
        id="collapsibleNavbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="#projects" class="login-btn">Login</a>
          </li>
          
        </ul>
      </div>
    </nav>

app/views/usuarios/create.html.erb
<h1>Usuarios#create</h1>
<p>Find me in app/views/usuarios/create.html.erb</p>

app/views/usuarios/index.html.erb
<div class="container">

  <h3>Candidatos encontrados</h3>
  <hr>
  <% @usuarios.each do |usuario| %>
  <h4><%= usuario.nome %></h4>
  <p>Desenvolvedor Java</p>
  <a href="#"><%= usuario.email %></a>
  <% end  %>
  <br>
  <%= link_to "Voltar", :back %>

</div>

app/views/usuarios/new.html.erb
<h1>Usuarios#new</h1>
<p>Find me in app/views/usuarios/new.html.erb</p>

app/views/vagas/index.html.erb
<div class="container">

  <h3>Vagas disponíveis</h3>
  <hr>
  <% @vagas.each do |vaga| %>
  <h4><%= vaga.nome %></h4>
  <p><%= vaga.skills %></p>
  <%= link_to "Ver candidatos", usuarios_path, class: "btn btn-info" %>
  <% end  %>
  <br>
  <%= link_to "Voltar", :back %>

</div>

app/views/vagas/new.html.erb
<h1>Formulário de Cadastro de Vaga</h1>

app/views/vagas/show.html.erb
<div class="container">

  <h1>Candidatos filtrados para esta vaga</h1>

  <% @usuarios.each do |usuario| %>
    <%= <h4> usuario.nome </h4> %>
    <%= <a href="#">usuario.email </a> %>
  <% end %>

</div>